data_root: null
results_root: "./results/"
benchmark_results_root: "./results/benchmark/"
benchmark_datasets:
  - fairface_margin025
  - fairface_margin125
  - miap
  - phase
  - pata
benchmark_tasks:
  - sentiment
  - skills
  - occupations
classification_datasets:
  - fairface_margin025
  - fairface_margin125
  - miap
  - phase
  - pata
  - idenprof
classification_attributes:
  - gender
  - ethnicity
  - occupation
